---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: blocky
    name: blocky
    namespace: core
    repo: https://k8s-at-home.com/charts/
    version: "10.1.0"
    valuesFile: values.yaml
