---
kind: Kustomization
namespace: core

helmCharts:
  - name: node-feature-discovery
    releaseName: node-feature-discovery
    repo: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    version: "0.11.1"

resources:
  - nfd-worker-conf-cm.yaml
