    image:
      repository: ghcr.io/0xerr0r/blocky
      tag: v0.19
    controller:
      enabled: true
      type: deployment
      strategy: RollingUpdate
      replicas: 2
    service:
      main:
        ports:
          http:
            port: 4000
      dns:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "192.168.10.132"
        ports:
          tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
          udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local
    config: |
      upstream:
        default:
          - tcp+udp:1.1.1.1
      conditional:
        mapping:
          pantheon.schouten-lebbing.nl: tcp+udp:192.168.10.231:53
      blocking:
        blackLists:
          ads:
            - https://raw.githubusercontent.com/ookangzheng/dbl-oisd-nl/master/dbl.txt
            - |
              /^ad([sxv]?[0-9]*|system)[_.-]([^.[:space:]]+\.){1,}|[_.-]ad([sxv]?[0-9]*|system)[_.-]/
              /^(.+[_.-])?adse?rv(er?|ice)?s?[0-9]*[_.-]/
              /^(.+[_.-])?telemetry[_.-]/
              /^adim(age|g)s?[0-9]*[_.-]/
              /^adtrack(er|ing)?[0-9]*[_.-]/
              /^advert(s|is(ing|ements?))?[0-9]*[_.-]/
              /^aff(iliat(es?|ion))?[_.-]/
              /^analytics?[_.-]/
              /^banners?[_.-]/
              /^beacons?[0-9]*[_.-]/
              /^count(ers?)?[0-9]*[_.-]/
              /^mads\./
              /^pixels?[-.]/
              /^stat(s|istics)?[0-9]*[_.-]/
        whiteLists:
          ads:
            - https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt
        clientGroupsBlock:
          default:
            - ads
      clientLookup:
        upstream: tcp+udp:192.168.10.1
      prometheus:
        enable: true
        path: /metrics
      bootstrapDns: tcp:1.1.1.1
      httpPort: 4000
      logFormat: json
      logLevel: info
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - blocky
              topologyKey: kubernetes.io/hostname
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 750Mi
