---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: rook-ceph
    name: rook-ceph
    namespace: rook-ceph
    repo: https://charts.rook.io/release
    version: "v1.9.8"
    valuesFile: values.yaml
