---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: nvidia-device-plugin
    name: nvidia-device-plugin
    namespace: core
    repo: https://nvidia.github.io/k8s-device-plugin
    version: "0.12.2"
    valuesFile: values.yaml
