---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: core
spec:
  destination:
    namespace: core
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: v1.7.1
    chart: cert-manager
    helm:
      valueFiles:
        - values.yaml
      values: |
        installCRDs: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
