---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default
spec:
  secretName: default-certificate
  commonName: "*.pantheon.schouten-lebbing.nl"
  dnsNames:
    - "*.pantheon.schouten-lebbing.nl"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
