---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  kustomize.buildOptions: --enable-alpha-plugins --enable-helm
  # url: https://argocd.pantheon.schouten-lebbing.nl
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
  server.staticassets: "/shared/app"
