# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-creds
stringData:
    email: ENC[AES256_GCM,data:4vjBIhK8WgptDcd8pRdnx6TIJ5LzpEfV8w==,iv:2e1j9/UKiF75/wb2vqWYKD30P/+qXwdNnL/sk4b7Zv8=,tag:LHGA8pyeUKLNJY3lEMeWSQ==,type:str]
    api-key: ENC[AES256_GCM,data:b5iMhw6R4XmI78mN3dIV/r/com2VwIxYqU7P9vHtjDNxnLTNgg==,iv:Bs+rWRYhPQgwCbfVFPnR61v0XUkf43mg58n2uUCnUzI=,tag:e1sZT7C6lYFI74PEADz2Eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-08-03T23:43:04Z"
    mac: ENC[AES256_GCM,data:TuuW+Wks6Cum0v09wZaz/G9s68p0OPpOA4wsJXvOOjq/WWEsMUAsOfbXUNxsItC4C2MGAM4PMrkTXBJqDouDr5m9ohgtyCDprMuxr1lwkq4ExygcihybAtBlS+NMLhI6Vs5eQc4gMTLL0uLP29ly4VoFLEfUEv4VRl0DYVSC1yk=,iv:ipayg9ROO/3WCBvYQgzny4f/ogbqyzkzbgYK56+1bac=,tag:pQfgC8er4UwQlyR7wayKnA==,type:str]
    pgp:
        - created_at: "2022-08-03T23:43:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2HEJcRig7GEARAAncqQGhXn4vn1uFylXZndmSPw/5cOTSeDqYqLRaJStG+s
            eW4YlWqk55eRPUxWxKH1rY8kJ5mMyF+W9KoODjtaO5+yvGUqaxUBAgbdL9pN0cEU
            m7ZUCLnVVaZM4/JxQmvN4bsW6udFUg2hf6+pdDL3IZ58OrVx5SkJKg1feX7OsFJZ
            smJcGMMwOn/ZQyjfwatbfnobi5sIAQKV2PjM4vF9qxzdbQXPysYbk5xp7aYL3RS+
            jwaS51i33RHI+aHLirjw1na0cO6BVeJd7oR/MHRvjEjzaLVaNOe6q49t+jlbZTDX
            UG81xscxH525/OSYJ+03zJ5hKrH83MWOjUnlR/dFKo/iM+rRP6N854BRaf0iYW/2
            204DAKQKaK0N/EEtScj0z2DAWPskwUpy3CTXl+R2FYFOY/uLd+ykoo4IKh1HdCEJ
            aFWDympiwa5DqIDxxCY96NOM3O2FBD6RbJ8YpgNtCJ1fSbAeNA+fJb9BNu0t6VVp
            hwdxYeO8v1PSnFWLtEAZPSufvOckJC4nzQEItkM1S21JrJY7+oq4sHT5xfNElo+4
            RPbtcXfOPoo1jT1w+JWO16N5z30rqVdtE513MY5ODAekY3MolB84ecibKB5x5R/d
            6T5kGA9/RLmH7k5lXBzOQYNz7gkVeLNNL7iWcCSOK/RxJbLEW9Lld1tt0xp6ZkLS
            XgHfe7p3BuK4xf8rB8zVcfcAOXiO+61+ImJ6b7Ti0RPdqzcVvxBzRUZ37zOyS2be
            j2ZTESbYR2leDn/I5JjF3mVIeXzoHtlP4d3Pzrz7hPxwAtSg41hL4CDDGLbDUvA=
            =Kcfm
            -----END PGP MESSAGE-----
          fp: 1B9AA9EB9919843CDD0B8983966F446F201E8DDD
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
