txtOwnerId: pantheon-schouten-lebbing.nl
txtPrefix: txt.
registry: txt
domainFilters:
  - schouten-lebbing.nl
  - pantheon.schouten-lebbing.nl

policy: sync
interval: 30s

crd:
  create: true

provider: cloudflare
env:
  - name: CF_API_EMAIL
    valueFrom:
      secretKeyRef:
        name: cloudflare-creds
        key: email
  - name: CF_API_KEY
    valueFrom:
      secretKeyRef:
        name: cloudflare-creds
        key: api-key

nodeSelector:
  kubernetes.io/arch: amd64
