---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "pihole"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Ornias1993/homelab-kube-cluster.git"
    path: manifests/workloads/pihole
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: pihole
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
