apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: action-runner-crds
  namespace: argocd
spec:
  project: "default"
  source:
    repoURL: https://github.com/Ornias1993/homelab-kube-cluster.git
    targetRevision: main
    path: 'manifests/actions-runner-system/actions-runner-controller/crds'
  destination:
    server: https://kubernetes.default.svc
    namespace: 'actions-runner-system'
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
