---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./secret-generator.yaml


helmCharts:
  - releaseName: actions-runner-controller
    name: actions-runner-controller
    namespace: actions-runner-system
    repo: https://actions-runner-controller.github.io/actions-runner-controller
    version: "0.20.2"
    valuesFile: values.yaml
    includeCRDs: true
