---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core

resources:
  - secret.sops.yaml

helmCharts:
  - releaseName: external-dns
    name: external-dns
    namespace: core
    repo: https://kubernetes-sigs.github.io/external-dns
    version: "10.24.0"
    valuesFile: values.yaml
