---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - ./secret-generator.yaml

helmCharts:
  - releaseName: external-dns
    name: external-dns
    namespace: core
    repo: https://kubernetes-sigs.github.io/external-dns
    version: "1.10.1"
    valuesFile: values.yaml
