---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: littlelink-kjeld
    name: littlelink
    namespace: public
    repo: https://k8s-at-home.com/charts/
    version: "10.4.8"
    valuesFile: values.yaml
