---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: argo-events
    name: argo-events
    namespace: argo-events
    repo: https://argoproj.github.io/argo-helm
    version: "2.0.3"
    valuesFile: values.yaml
