service:
  main:
    type: LoadBalancer
    ports:
      main:
        protocol: UDP
        port: 53
        targetPort: 53
        loadBalancerIP: "192.168.10.242"

# -- list of processed domains
domains:
  # -- Delegated domain
  - domain: "pantheon.schouten-lebbing.nl"
    # -- Optional configuration option for DNS01 challenge that will redirect all acme
    # challenge requests to external cloud domain (e.g. managed by cert-manager)
    # See: https://cert-manager.io/docs/configuration/acme/dns01/
    dnsChallenge:
      enabled: false
      domain: dns01.clouddns.com
