---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: website-release-runner
spec:
  replicas: 2
  template:
    spec:
      repository: truecharts/website
      labels:
        - website-release-runner
