---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mainpool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.10.230-192.168.10.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisel2
  namespace: metallb-system
spec:
  ipAddressPools:
  - mainpool
