---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: k8s-gateway
    name: k8s-gateway
    namespace: core
    repo: https://kubernetes-sigs.github.io/external-dns
    version: "6.1.8"
    valuesFile: values.yaml
