---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: kms
    name: kms
    namespace: private
    repo: https://charts.truecharts.org
    version: "11.0.24"
    valuesFile: values.yaml
