---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "argocd"
  namespace: core
spec:
  project: default
  source:
    repoURL: "https://github.com/Ornias1993/homelab-kube-cluster.git"
    path: manifests/bootstrapping/00-argocd
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: core
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
