apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    kubevirt.ui/provider: fedora
  name: fedora
spec:
  pvc:
    storageClassName: openebs-hostpath
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  source:
    http:
      url: https://download.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/x86_64/images/Fedora-Cloud-Base-35-1.2.x86_64.raw.xz
